// Generated by `yarn new:queryMock`
import { graphql, HttpResponse } from 'msw';
import { data } from './data';
import type { Options, Query } from './type';

export const workspaceQuery = (options?: Options) => {
  return graphql.query<Query>('Workspace', () => {
    if (options?.networkError) {
      return HttpResponse.json({
        errors: [
          {
            message: 'Network request failed',
          },
        ],
      });
    }

    return HttpResponse.json({
      data: data(options?.res, options?.deepMergeOptions),
    });
  });
};
