import {
  AiFillCheckCircle,
  AiFillLike,
  AiFillPlayCircle,
  AiOutlineFilePdf,
  AiOutlineFileText,
  AiOutlineLike,
  AiOutlineProject,
} from 'react-icons/ai';
import {
  BiArrowToRight,
  BiAt,
  BiBarChart,
  BiBeenHere,
  BiBell,
  BiBookAdd,
  BiBookOpen,
  BiCalendar,
  BiCalendarAlt,
  BiCheck,
  BiCheckCircle,
  BiChevronDown,
  BiChevronLeft,
  BiChevronRight,
  BiCodeAlt,
  BiCommentDots,
  BiCompass,
  BiCopyAlt,
  BiCustomize,
  BiDetail,
  BiDotsHorizontalRounded,
  BiDownArrowAlt,
  BiDownload,
  BiEditAlt,
  BiExpand,
  BiFileBlank,
  BiFilter,
  BiFilterAlt,
  BiGitPullRequest,
  BiGridAlt,
  BiGridHorizontal,
  BiGridVertical,
  BiGroup,
  BiHelpCircle,
  BiHome,
  BiIdCard,
  BiImageAlt,
  BiInfoCircle,
  BiLayerPlus,
  BiLayout,
  BiLeftArrowAlt,
  BiLeftIndent,
  BiLink,
  BiLinkExternal,
  BiListOl,
  BiListPlus,
  BiListUl,
  BiLockAlt,
  BiMenu,
  BiMessageRounded,
  BiMessageRoundedDots,
  BiMobile,
  BiMoveVertical,
  BiMovie,
  BiNotification,
  BiPause,
  BiPencil,
  BiPhotoAlbum,
  BiPlay,
  BiPlayCircle,
  BiPlus,
  BiRightIndent,
  BiRocket,
  BiSave,
  BiSearch,
  BiShapePolygon,
  BiSliderAlt,
  BiSort,
  BiSpreadsheet,
  BiSquareRounded,
  BiStrikethrough,
  BiSubdirectoryRight,
  BiSun,
  BiTable,
  BiTask,
  BiTime,
  BiTrash,
  BiTrashAlt,
  BiUnlink,
  BiUser,
  BiUserPlus,
  BiX,
} from 'react-icons/bi';
import { BsTagFill } from 'react-icons/bs';
import { FaGithub, FaMoon, FaRegStar, FaStar, FaTwitter } from 'react-icons/fa';
import { FiBold, FiItalic, FiUnderline } from 'react-icons/fi';
import { HiOutlineEmojiHappy, HiOutlineMail } from 'react-icons/hi';
import { IoMdAttach } from 'react-icons/io';
import { MdSort, MdTextFormat } from 'react-icons/md';
import { TiFlowChildren } from 'react-icons/ti';

export const icons = {
  arrowDownAlt: BiDownArrowAlt,
  arrowLeftAlt: BiLeftArrowAlt,
  arrowToRight: BiArrowToRight,
  at: BiAt,
  attach: IoMdAttach,
  barChart: BiBarChart,
  beenHere: BiBeenHere,
  bell: BiBell,
  bold: FiBold,
  bookAdd: BiBookAdd,
  bookOpen: BiBookOpen,
  calendar: BiCalendar,
  calendarAlt: BiCalendarAlt,
  check: BiCheck,
  checkCircle: BiCheckCircle,
  checkCircleFilled: AiFillCheckCircle,
  chevronDown: BiChevronDown,
  chevronLeft: BiChevronLeft,
  chevronRight: BiChevronRight,
  codeAlt: BiCodeAlt,
  commentDots: BiCommentDots,
  compass: BiCompass,
  copyAlt: BiCopyAlt,
  customize: BiCustomize,
  detail: BiDetail,
  dotsHorizontalRounded: BiDotsHorizontalRounded,
  download: BiDownload,
  editAlt: BiEditAlt,
  emojiHappy: HiOutlineEmojiHappy,
  fileBlank: BiFileBlank,
  fillLike: AiFillLike,
  filter: BiFilter,
  filterAlt: BiFilterAlt,
  flowChildren: TiFlowChildren,
  fullscreenOutline: BiExpand,
  gitPullRequest: BiGitPullRequest,
  github: FaGithub,
  gridAlt: BiGridAlt,
  gridHorizontal: BiGridHorizontal,
  gridVertical: BiGridVertical,
  group: BiGroup,
  help: BiHelpCircle,
  home: BiHome,
  idCard: BiIdCard,
  imageAlt: BiImageAlt,
  infoCircle: BiInfoCircle,
  italic: FiItalic,
  layerPlus: BiLayerPlus,
  layout: BiLayout,
  leftIndent: BiLeftIndent,
  link: BiLink,
  linkExternal: BiLinkExternal,
  listOl: BiListOl,
  listPlus: BiListPlus,
  listUl: BiListUl,
  lockAlt: BiLockAlt,
  mailOutline: HiOutlineMail,
  menu: BiMenu,
  messageRounded: BiMessageRounded,
  messageRoundedDots: BiMessageRoundedDots,
  mobile: BiMobile,
  moon: FaMoon,
  moveVertical: BiMoveVertical,
  movie: BiMovie,
  notification: BiNotification,
  outlineFilePdf: AiOutlineFilePdf,
  outlineFileText: AiOutlineFileText,
  outlineLike: AiOutlineLike,
  outlineProject: AiOutlineProject,
  pause: BiPause,
  pencil: BiPencil,
  photoAlbum: BiPhotoAlbum,
  play: BiPlay,
  playCircle: AiFillPlayCircle,
  playCircleOutline: BiPlayCircle,
  plus: BiPlus,
  tag: BsTagFill,
  rightIndent: BiRightIndent,
  rocket: BiRocket,
  save: BiSave,
  search: BiSearch,
  shapePolygon: BiShapePolygon,
  sliderAlt: BiSliderAlt,
  sort2: BiSort,
  sort: MdSort,
  spreadsheet: BiSpreadsheet,
  squareRounded: BiSquareRounded,
  starFilled: FaStar,
  starOutline: FaRegStar,
  strikethrough: BiStrikethrough,
  subdirectoryRight: BiSubdirectoryRight,
  sun: BiSun,
  table: BiTable,
  task: BiTask,
  textFormat: MdTextFormat,
  time: BiTime,
  trash: BiTrash,
  trashAlt: BiTrashAlt,
  twitter: FaTwitter,
  underline: FiUnderline,
  unlink: BiUnlink,
  user: BiUser,
  userPlus: BiUserPlus,
  x: BiX,
} as const;

export type IconType = keyof typeof icons;
